const CertificateData = [
    {"Cname": "SYT company Co., Ltd.", "Reg": "KR", "Cnum": "D-C-01-KR-01-01", "Std": "Certificate of Verification (Design Appraisal)", "Fno": "D-C-01-KR-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "SYT company Co., Ltd.", "Reg": "KR", "Cnum": "D-C-01-KR-01-02", "Std": "Certificate of Verification (Design Appraisal)", "Fno": "D-C-01-KR-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "SYT company Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011- 09589", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-01-KR-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "SYT company Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011-09590", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-01-KR-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "WEMARK ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "030-03-011-09074", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-01-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240716-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "KANGWON ENERGY CO., LTD", "Reg": "KR", "Cnum": "nan", "Std": "nan", "Fno": "D-C-02-KR-01", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "CAELUM Co., Ltd.", "Reg": "KR", "Cnum": "nan", "Std": "nan", "Fno": "D-C-03-KR-01", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "WEMARK ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "030-03-011-09125", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-01-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "030-03-011-09137", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Sri Binamech Engineering Sdn Bhd", "Reg": "MYL", "Cnum": "030-03-011-09159", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-03-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "030-03-011-09165", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-03", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "030-03-011-09136", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "SAK-82-096-240801-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "LFG ENGINEERING AND SERVICES SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-240820-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-05-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240902-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-04", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240902-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-05", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240902-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-06", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240827-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-07", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Superscape Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240902-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-06-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240924-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-08", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "PROWELD TRAINING CENTRE SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-240912-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-07-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Group Technical Inspection(GTI) Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-08-MY-01", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240912-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-09", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240912-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-10", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Trust Vision Technology Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240924-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-09-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "GRACE FIELD CORPORATION SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-240924-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-10-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241007-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-11", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-240925-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-12", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241004-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-13", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "PROWELD TRAINING CENTRE SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-241004-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-07-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "SAK-82-096-241004-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-03", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241014-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-14", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241014-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-15", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "PROWELD TRAINING CENTRE SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-241018-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-07-MY-03", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Sri Binamech Engineering Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-03-MY-02", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "Sri Binamech Engineering Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241030-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-03-MY-03", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241030-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-16", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241104-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-17", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241118-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-18", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "SAK-82-096-241118-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-04", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "SAK-82-096-241118-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-05", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241118-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-19", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241128-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-20", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Trust Vision Technology Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241218-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-09-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "DEVMAN ENGINEERING", "Reg": "MYL", "Cnum": "SAK-82-096-241127-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-11-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "SYNCHONG HOE ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-241206-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-12-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "A-Plus Manufacturing Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-11-241218-1", "Std": "Certificate of Compliance", "Fno": "D-C-12-MY-01", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "A-Plus Manufacturing Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-097-241218-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-13-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241230-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-21", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-241227-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-22", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250124-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-23", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250213-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-23", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "KEMUNING ENGINEERING Sdn Bhd\n(VENTAGE STEEL)", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-14-MY-01", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "KEMUNING ENGINEERING Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-14-MY-02", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "KEMUNING ENGINEERING Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-14-MY-03", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "KEMUNING ENGINEERING Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-14-MY-04", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "KEMUNING ENGINEERING Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-14-MY-05", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "KEMUNING ENGINEERING Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-14-MY-06", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "CTECH INDUSTRIAL SUPPLIES AND MACHINERY", "Reg": "MYL", "Cnum": "SAK-82-096-250107-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-15-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "SA MAINTENANCE & SERVICES (M) SDN. BHD", "Reg": "MYL", "Cnum": "nan", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-16-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-5", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-6", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-7", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-8", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-9", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-10", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-11", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-12", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-13", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-14", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-15", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-16", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-17", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-18", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-19", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250210-20", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250220-11", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250220-12", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250220-13", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "MATRIX SYNERGY ENGINEERING SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250220-14", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-17-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "IP Solutions (JM0431283-X)", "Reg": "MYL", "Cnum": "SAK-82-096-250220-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-18-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "IP Solutions (JM0431283-X)", "Reg": "MYL", "Cnum": "SAK-82-096-250220-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-18-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "IP Solutions (JM0431283-X)", "Reg": "MYL", "Cnum": "SAK-82-096-250220-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-18-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Superscape Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250107-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-06-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250206-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-24", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-02-MY-25", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "SAK-82-096-250207-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-06", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Superscape Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-06-MY-03", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250204-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-27", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "AMZ NDT SERVICES", "Reg": "MYL", "Cnum": "SAK-82-096-250310", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-19-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Chalice Quality Service Partner Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250206-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-20-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250224-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-28", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250224-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-29", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-30", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250224-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-31", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Trust Vision Technology Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250213-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-09-MY-03", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250211-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-32", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "REDMARK INDUSTRY SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250218-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-21-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "REDMARK INDUSTRY SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250218-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-21-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "REDMARK INDUSTRY SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250218-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-21-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "REDMARK INDUSTRY SDN BHD", "Reg": "MYL", "Cnum": "SAK-82-096-250218-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-21-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-5", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-6", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-7", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-8", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-9", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250220-10", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-33", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "One Dental Supply & Marketing Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-22-MY-01", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "Eka Raya Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250224-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-23-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Green Earth Engineering Services", "Reg": "MYL", "Cnum": "nan", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-24-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JSG Syntech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250304-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-25-MY-01", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "PROWELD TRAINING CENTRE SDN BHD", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-07-MY-04", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "Trust Vision Technology Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250318-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-09-MY-04", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Trust Vision Technology Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250318-3-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-09-MY-04", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250318-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-34", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250318-5", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-02-MY-35", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Globtech Engineering", "Reg": "MYL", "Cnum": "SAK-82-096-250318-6", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-04-MY-07", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JSG Syntech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250307", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-25-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "DEVMAN ENGINEERING", "Reg": "MYL", "Cnum": "SAK-82-096-250318-7", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-11-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "DEVMAN ENGINEERING", "Reg": "MYL", "Cnum": "SAK-82-096-250318-7-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-11-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "DEVMAN ENGINEERING", "Reg": "MYL", "Cnum": "SAK-82-096-250318-7-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-11-MY-02", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-02-MY-36", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "JSG Syntech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250318-8", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-25-MY-03", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JSG Syntech Sdn Bhd", "Reg": "MYL", "Cnum": "SAK-82-096-250318-9", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "D-C-25-MY-04", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TS Multitech Sdn Bhd", "Reg": "MYL", "Cnum": "nan", "Std": "nan", "Fno": "D-C-02-MY-37", "Cstat": "Invalid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-5", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-6", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-7", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-8", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-9", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-10", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-11", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-07-241114-12", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241111-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241111-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241111-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241205-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-5", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-6", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-7", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-8", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-9", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-10", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-096-240911-11", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-093-241021-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011-09596", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011-09597", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011-09598", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011-09599", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241220-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241220-2", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241220-3", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-241220-4", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-094-241125-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-093-241211-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "DAEBO Magnetic Co., Ltd.", "Reg": "KR", "Cnum": "082-03-011-09594", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "TAIHAN Engineering Co., Ltd.", "Reg": "KR", "Cnum": "SAK-82-092-250122-1", "Std": "Standard THIRD PARTY INSPECTION (TPI)", "Fno": "-", "Cstat": "Valid", "Cdate": ""},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01389", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01390", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01391", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01392", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01393", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01399", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01394", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01395", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01396", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01397", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "JEIL M&S Co., Ltd.", "Reg": "KR", "Cnum": "082-03026-01398", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "20/11/2027"},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01425", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "03/12/2029"},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01426", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "03/12/2029"},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01427", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "03/12/2029"},
    {"Cname": "Global Technology Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01428", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "03/12/2029"},
    {"Cname": "DAE BO Magnetic Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01424", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "04/12/2029"},
    {"Cname": "3GF Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01406", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "23/10/2025"},
    {"Cname": "3GF Co., Ltd.", "Reg": "KR", "Cnum": "082-03-026-01407", "Std": "Certificate of Compliance", "Fno": "-", "Cstat": "Valid", "Cdate": "23/10/2025"}
];
